on:
  pull_request:
    branches:
      - "main"
      - "feature/*"
      - "feature_engineering"
      - "create_actions_workflow"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --with ci

      - name: Run Unit Tests
        run: poetry run pytest src

      - name: Run mypy
        run: poetry run mypy src

      - name: Run pylint
        run: poetry run pylint --rcfile=.pylintrc src

      - name: Run coverage
        run: |
          poetry run coverage run -m pytest src 
          poetry run coverage report 
          poetry run coverage html

      - name: Run pyinstrument profiler
        run: |
          for file in $(find src -name "*.py"); do
            poetry run pyinstrument $file --html -o pyinstrument_${file//\//_}.html || true
          done
