on:
  pull_request:
    branches:
      - "main"
      - "feature/*"
      - "feature_engineering"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5

      - name: Run Unit Tests
        run: pytest src

      - name: Run mypy
        run: mypy src

      - name: Run pylint
        run: pylint src

      - name: Run coverage
        run: coverage run -m pytest src && coverage report && coverage html

      - name: Run pyinstrument profiler
        run: |
          for file in $(find src -name "*.py"); do
            pyinstrument $file --html -o pyinstrument_${file//\//_}.html || true
          done